apiVersion: v1
kind: Secret
metadata:
  name: wordpress-db-secret
type: Opaque
data:
  mysql-root-password: YWRtaW4=
  mysql-database: ZGJfd29yZHByZXNz
  mysql-user: YWRtaW4=
  mysql-password: cGFzc3dvcmQ=